# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_email}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Ogata"]
  s.date = %q{2009-09-13}
  s.description = %q{Adds a thin abstraction on top of ActionMailer, which provides AR-like email models (with validations, callbacks, associations, protection from mass-assignment, etc.).  This allows your email actions to flow much the same as ActiveRecord ones.  On the testing side, ActiveEmail provides EmailRat, a Webrat-like agent for receiving email, for integration testing.
}
  s.email = %q{george.ogata@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "DESCRIPTION.txt",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "active_email.gemspec",
     "init.rb",
     "install.rb",
     "lib/active_email.rb",
     "lib/active_email/active_record_base_without_table.rb",
     "lib/active_email/email.rb",
     "lib/active_email/email_rat.rb",
     "lib/active_email/helper.rb",
     "lib/active_email/mailer.rb",
     "lib/active_email/rspec.rb",
     "lib/active_email/rspec/matchers.rb",
     "spec/email_rat_spec.rb",
     "spec/email_spec.rb",
     "spec/helper_spec.rb",
     "spec/helpers/temporary_directory.rb",
     "spec/helpers/temporary_email_class.rb",
     "spec/mailer_spec.rb",
     "spec/rspec_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec_integration/application_template.rb",
     "spec_integration/files/app/controllers/greetings_controller.rb",
     "spec_integration/files/app/emails/greeting.rb",
     "spec_integration/files/app/helpers/application_helper.rb",
     "spec_integration/files/app/views/emails/greeting.erb",
     "spec_integration/files/app/views/greetings/new.html.erb",
     "spec_integration/files/app/views/layouts/application.html.erb",
     "spec_integration/files/config/routes.rb",
     "spec_integration/files/spec/integration/sending_a_greeting_spec.rb",
     "spec_integration/files/spec/spec_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/oggy/active_email}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Makes using ActionMailer suck less.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/email_rat_spec.rb",
     "spec/helper_spec.rb",
     "spec/mailer_spec.rb",
     "spec/rspec_spec.rb",
     "spec/email_spec.rb",
     "spec/helpers/temporary_email_class.rb",
     "spec/helpers/temporary_directory.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 1.2.8"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.7"])
      s.add_runtime_dependency(%q<actionmailer>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["= 1.2.8"])
      s.add_dependency(%q<mocha>, ["= 0.9.7"])
      s.add_dependency(%q<actionmailer>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 1.2.8"])
    s.add_dependency(%q<mocha>, ["= 0.9.7"])
    s.add_dependency(%q<actionmailer>, [">= 0"])
  end
end
