# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy_mailer}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Ogata"]
  s.date = %q{2009-09-03}
  s.description = %q{Adds a thin abstraction on top of ActionMailer, which provides AR-like email models (with validations, callbacks, associations, protection from mass-assignment, etc.).  This allows your email actions to flow much the same as ActiveRecord ones.  On the testing side, EasyMailer provides EmailRat, a Webrat-like agent for receiving email, for integration testing.
}
  s.email = %q{george.ogata@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/easy_mailer.rb",
     "lib/easy_mailer/base.rb",
     "lib/easy_mailer/email_rat.rb",
     "lib/easy_mailer/helper.rb",
     "lib/easy_mailer/rspec.rb",
     "lib/easy_mailer/rspec/matchers.rb",
     "spec/base_spec.rb",
     "spec/email_rat_spec.rb",
     "spec/lib/test_mailer.rb",
     "spec/rspec_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/views/test_mailer/greeting.erb",
     "tasks/easy_mailer_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/oggy/easy_mailer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Makes using ActionMailer suck less.}
  s.test_files = [
    "spec/base_spec.rb",
     "spec/email_rat_spec.rb",
     "spec/lib/test_mailer.rb",
     "spec/rspec_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<actionmailer>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<actionmailer>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<actionmailer>, [">= 0"])
  end
end
